import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }]
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api' }]
    }
  ]
};

export default sidebars;
